package code;

public enum ReqType {
	GENED_TIER1,
	GENED_TIER1_ENG,
	GENED_WI,
	GENED_TIER1_MAT,
	GENED_TIER1_WSM,
	GENED_TIER1_LST,
	GENED_TIER1_FLG,
	GENED_TIER2_SCI_INQ,

	GENED_TIER2_HIST_PERSP,
	GENED_TIER2_FQV,
	GENED_TIER2_ART_LIT,
	GENED_TIER2_SOC_DISP,

	GENED_TIER2_CULT_FLG,
	GENED_TIER2_CULT_NONWEST,
	GENED_TIER3_INTEG,
	MAJOR_CSC,
	MAJOR_CSC_ELECT1,
	MAJOR_CSC_ELECT2,
	MAJOR_CSC_ELECT3
}
